# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-01 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='commoditybase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('pf', models.CharField(max_length=2)),
                ('c_type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=1000, null=True)),
                ('latlng', models.CharField(max_length=1000)),
                ('other_keys', models.CharField(max_length=1000, null=True)),
                ('other_values', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='nearbybase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('n_type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=1000, null=True)),
                ('latlng', models.CharField(max_length=1000)),
                ('other_keys', models.CharField(max_length=1000, null=True)),
                ('other_values', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='staionbase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=100)),
                ('entry_keys', models.CharField(max_length=1000)),
                ('entry_values', models.CharField(max_length=1000)),
                ('exit_keys', models.CharField(max_length=1000)),
                ('exit_values', models.CharField(max_length=1000)),
                ('commodity_keys', models.CharField(max_length=1000, null=True)),
                ('nearby_keys', models.CharField(max_length=1000, null=True)),
                ('pf_number', models.CharField(max_length=2)),
                ('pf_types', models.CharField(max_length=4)),
                ('ticket_counter_keys', models.CharField(max_length=1000, null=True)),
                ('ticket_counter_values', models.CharField(max_length=1000, null=True)),
                ('reservation_charts', models.CharField(max_length=1000, null=True)),
                ('waiting_room_keys', models.CharField(max_length=1000, null=True)),
                ('waiting_room_values', models.CharField(max_length=1000, null=True)),
                ('cloak_room', models.CharField(max_length=1000, null=True)),
                ('rpf_office', models.CharField(max_length=1000, null=True)),
                ('grp_office', models.CharField(max_length=1000, null=True)),
                ('enquiry_office', models.CharField(max_length=1000, null=True)),
                ('railway_engg', models.CharField(max_length=1000, null=True)),
                ('station_master', models.CharField(max_length=1000, null=True)),
                ('tte_office', models.CharField(max_length=1000, null=True)),
                ('pf_stair_entries', models.CharField(max_length=1000, null=True)),
                ('pf_under_entries', models.CharField(max_length=1000, null=True)),
                ('pf_slope_entries', models.CharField(max_length=1000, null=True)),
                ('pf_escl_entries', models.CharField(max_length=1000, null=True)),
                ('divyang_keys', models.CharField(max_length=1000, null=True)),
                ('divyang_values', models.CharField(max_length=1000, null=True)),
                ('other_keys', models.CharField(max_length=1000, null=True)),
                ('other_values', models.CharField(max_length=1000, null=True)),
                ('has_protected', models.CharField(max_length=1)),
                ('is_railwired', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='trnpf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('pf', models.CharField(max_length=2)),
                ('trains', models.CharField(max_length=1000)),
            ],
        ),
    ]
