# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-01 03:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apibase', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='staionbase',
            new_name='stationbase',
        ),
    ]
